FROM public.ecr.aws/lambda/python:3.12

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR ${LAMBDA_TASK_ROOT}

COPY pyproject.toml ./
RUN pip install --no-cache-dir .

COPY app ./app

CMD ["app.lambda_handler.handler"]
